### ISSUE TITLE
Exclude Severities Input Causing Failures

### ISSUE THREAD

**Issue by cotton5parrot** [CrowdStrike/fcs-action#24]
The `exclude_severities` input is causing the GitHub action to fail in our pipelines:

```
-------- FCS CLI --------
Error: unknown argument(s) for --exclude-severities: low, info
```

This is how I am using it: `exclude_severities: "low,info"`

This only started happening last night, prior to this the Github action had been working flawlessly, nothing has changed in our end.

**Comment by carlosmmatos** [comment]
@cotton5parrot do you happen to know what version you are using?

**Comment by carlosmmatos** [comment]
Based on the latest v1.0.0 - I see the following:
```
      --exclude-severities strings   exclude results with provided severities from scan
                                     allowed values: critical, high, medium, informational
```

and from 0.47.1 - I see the following:
```
      --severities strings           include results by providing specific severities
                                     allowed values: high, medium, low, info
                                     example: 'high,low'
```

So looks like they changed the allowed values which might be why you are seeing that. I would try either 

- updating your values to: `exclude_severities: "medium,informational"`
- or pinning the version to 0.47.1: `version: 0.47.1`

I will ask engineering why they changed it and what happened to low 🤷‍♂

**Comment by carlosmmatos** [comment]
@cotton5parrot - I verified this is part of the new major release v1.0.0

Release notes here: https://falcon.crowdstrike.com/support/release-notes/release-notes-manage-infrastructure-as-code-rules-in-falcon-cloud-security

You can see the updated the sev values.

**Comment by cotton5parrot** [comment]
@carlosmmatos - Thanks for the above, I can confirmed I am using v1.0.6 `crowdstrike/fcs-action@v1.0.6`. I have updated our GitHub action to use the new values. 

The `README` still references the old values, I have created a PR to update the reference the new values: https://github.com/CrowdStrike/fcs-action/pull/25.

**Comment by carlosmmatos** [comment]
@cotton5parrot so it's not related to the version of the this GitHub action which is the reason I haven't updated the README's yet. It has to do with the version of the FCS utility itself, which is managed by the `version` input parameter. I appreciate the PR but I will probably end up updating it once I determine the best path forward to notate the changes based on the FCS utility, not the gh action.

**Comment by cotton5parrot** [comment]
@carlosmmatos Ah I see thankyou for confirming. 

Not a problem - the reason for the PR was because the version pinned in the usage step `crowdstrike/fcs-action@v1.0.6` will use the new input values and not the old ones mentioned in the inputs section. 

All good, thanks for the assist above 😄

**Comment by carlosmmatos** [comment]
No, that's my point - it has nothing to do with the version of the fcs-action. The issue is that the version of the fcs cli changed, not the github action. So depending on which fcs cli version a user is working with, will dictate the allowed values.. here is an example to better illustrate:

---
**This will fail because by default, if you don't specify a `version`, it will use the latest version for the FCS CLI (which is 1.0.0).**

> Per the release notes I pinned, they changed the severities so the below will fail because low is not a valid value

```yaml
- name: Run FCS IaC Scan
  uses: crowdstrike/fcs-action@v1.0.6
  with:
    falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
    falcon_region: 'us-2'
    path: './kubernetes'
    severities: 'medium,low'
  env:
    FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
```

**This will work, because we are specifying an older version (0.47.1) of the FCS CLI which still supports low severity as a valid value**

```yaml
- name: Run FCS IaC Scan
  uses: crowdstrike/fcs-action@v1.0.6
  with:
    falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
    falcon_region: 'us-2'
    version: 0.47.1
    path: './kubernetes'
    severities: 'medium,low'
  env:
    FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
```

So you can see that the version of the GitHub action does not matter - they are both using `uses: crowdstrike/fcs-action@v1.0.6`. What actually matters is the CLI version.
